### ISSUE TITLE
Issue when adding discussion balloons

### ISSUE THREAD

**Issue by noobishme** [sylque/discpage#29]
The Readme instructions say this... (and following these, **_I could not_** get any balloons to appear)...
```
To add a balloon, add [dpgb id=myBalloonId][/dpgb] to your topic text. For example:

## Introduction [dpgb id=intro][/dpgb]
```

However a balloon does appear at the end of any block of text that I wrap (in between the tags) like so ...

[dpgb id=myballoonid] **_The section I want to highlight when the balloon is clicked, for my users to comment on, is wrapped here in between these tags_** [/dpgb]

For example:

**[dpgb id=intro]** Introduction **[/dpgb]**

**Comment by sylque** [comment]
Thanks @noobishme.

In fact there are 2 issues here: 

1. Inserting `[dpgb id=myBalloonId][/dpgb]` at the end of a heading (in order to select the heading and following paragraphs, as documented [here](https://github.com/sylque/discpage#adding-discussion-balloons-to-a-static-page)) doesn’t work anymore. 

2. Placing `[dpgb id=myBalloonId]Some text here[/dpgb]` around a text (in order to select that text only) is undocumented.

**Comment by noobishme** [comment]
Thank you @sylque -- please do let me know how I can help with debugging.

I have a testing instance at https://noobish.me/t/chapter-1-in-the-beginning/255

**Comment by sylque** [comment]
Regarding my point 1 above, I posted a bug report for the Discourse team (see [here](https://meta.discourse.org/t/markdown-extension-inline-wrap-functions-doesnt-recognize-bbcode-tags-with-empty-content-anymore/238894)).

Regarding my point 2, I improved the DiscPage documentation (see [here](https://github.com/sylque/discpage/blob/master/README.md#adding-discussion-balloons-to-a-static-page)).

**Comment by sylque** [comment]
The bug is now fixed in Discourse (see https://github.com/discourse/discourse/pull/18276).

Please install the latest Discourse version and rebuild the pages containing "balloons on headings". This is done either:
1. by modifying the page and click "Save Edit", or 
2. by clicking Alt+a to enter DiscPage debug mode, then by clicking the wrench icon at the bottom of the post (not the one at the bottom of the entire topic!), then by clicking "Rebuild HTML" 
![image](https://user-images.githubusercontent.com/42490951/191229958-84606248-a33e-4e6d-a0bc-d113f2e4f3ef.png)

@noobishme, do you confirm it's fixed?

**Comment by noobishme** [comment]
Yes I have tested and do confirm -- the fix is in for this issue!

(However, I still can't use this plugin because the Layouts Plugin is still preventing the “tag” field from being prefilled in the composer when creating a new Topic from a Tag page as reported here: https://meta.discourse.org/t/layouts-plugin/55208/367)
